name: Static ci/cd deployment

on:
    push:
        branches: [main]

permissions:
    id-token: write
    contents: read
    

jobs:
    terraform-deploy:
        runs-on: ubuntu-latest

        steps:

            -   name : Checkout code
                uses: actions/checkout@v4

            -   name: Configure the AWS credentials
                uses: aws-actions/configure-aws-credentials@v4
                with:
                    role-to-assume: ${{secrets.AWS_ROLE_ARN}}
                    aws-region: ${{secrets.AWS_REGION}}
                
            -   name: Sync files to S3
                run: |
                    aws s3 sync . s3://${{secrets.S3_BUCKET}}/ \
                    --delete \
                    --cache-control "public, max-age=3600"

            -   name: Invalidate CloudFront cache
                run: |
                    aws cloudfront create-invalidation \
                    -- distribution-id ${{secrets.CLOUDFRONT_ID}} \
                    --paths "/*"

            -   name: Deployment Overview
                run: |
                    echo "Website deployment successful" 
                    echo "https://${{secrets.CLOUDFRONT_URL}}"




    